services:
  broker:
    build:
      context: .
      dockerfile: broker/Dockerfile
    ports:
      - "6767:6767"
      # :^)

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "6969:6969"
    depends_on:
      - broker
