services:
  broker:
    build:
      context: .
      dockerfile: broker/Dockerfile
    ports:
      - "6767:6767"
      # :^)
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6767"]
      interval: 60m
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 1s
  server1:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "6969:6969"
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - PORT=6969
  server2:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "9696:9696"
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - PORT=9696
